name: Test

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: ['2.6', '2.7']

    steps:
      - uses: actions/checkout@v2

      - name: Set up Ruby ${{ matrix.ruby }}
        uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}

      - name: Retrieve gems cache
        uses: actions/cache@v1.1.2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-v2-${{ matrix.ruby }}-gem-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-v2-${{ matrix.ruby }}-gem-

      - name: Install gems
        run: |
          gem install bundler:2.0.0
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3

      - name: Install dummy dependencies
        run: cd test/dummy && bundle install && yarn install

      - name: Run tests
        run: bin/test

      - name: Upload log if failure
        uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: test.log
          path: test/dummy/log/test.log
